# ==========================================================================
# OBSIDIAN NVIM INTEGRATION
# ==========================================================================
# Neovim plugin layer for Obsidian vaults. Generates lazy.nvim plugin specs
# + blink-cmp bibtex source + obsidian_ls LSP registration as Lua files,
# then merges them into the nvim config directory via a home.activation hook.
#
# ARCHITECTURE: The base nvim config deploys via xdg.configFile."nvim"
# which creates a store symlink. Feature modules use home.activation hooks
# to resolve the symlink, copy the directory, and layer feature files on top.
# When this module is NOT imported, no research files exist — zero cost.
#
# NOTE: This module handles nvim integration only. Obsidian itself is
# installed separately (flatpak). CLI access via ~/.local/bin/obsidian.
# ==========================================================================
{ inputs, ... }: {
  flake.modules.homeManager.obsidian =
    { config, lib, pkgs, ... }:
    let
      vaultPath = "~/Documents/me/vault";

      researchInitLua = ''
        -- Research feature: obsidian.nvim + blink-cmp-bibtex + obsidian_ls
        -- Generated by modules/research/obsidian.nix — do not edit manually.

        -- Discover .bib files scoped to the current buffer's vault.
        -- Walks up from the buffer directory collecting *.bib at each level,
        -- stopping at the vault root (directory containing .obsidian/).
        -- Passed as a function to global_files — blink-cmp-bibtex calls it
        -- per buffer with the buffer number.
        local function discover_bib_files(bufnr)
          local ok, result = pcall(function()
            local bufname = bufnr and vim.api.nvim_buf_is_valid(bufnr)
              and vim.api.nvim_buf_get_name(bufnr) or ''''''
            if bufname == '''' then
              return {}
            end
            local dir = vim.fn.fnamemodify(bufname, ':h')
            local bibs = {}
            local current = dir
            while current and current ~= '''' and current ~= '/' do
              local matches = vim.fn.glob(current .. '/*.bib', false, true)
              for _, f in ipairs(matches) do
                bibs[#bibs + 1] = vim.fn.expand(f)
              end
              if vim.fn.isdirectory(current .. '/.obsidian') == 1 then
                break
              end
              current = vim.fn.fnamemodify(current, ':h')
            end
            return bibs
          end)
          if not ok then
            return {}
          end
          return result
        end

        return {
          plugins = {
            {
              "obsidian-nvim/obsidian.nvim",
              version = "*",
              ft = "markdown",
              dependencies = { "nvim-lua/plenary.nvim" },
              keys = {
                { "gl", "<cmd>Obsidian follow_link<cr>", desc = "Obsidian Follow Link" },
                { "[o", "<cmd>Obsidian nav_link prev<cr>", desc = "Obsidian Previous Link" },
                { "]o", "<cmd>Obsidian nav_link next<cr>", desc = "Obsidian Next Link" },
              },
              opts = {
                legacy_commands = false,
                frontmatter = { enabled = false },
                checkbox = {
                  create_new = false,
                  order = { " ", "x" },
                },
                workspaces = {
                  { name = "me", path = "${vaultPath}" },
                  { name = "test", path = "~/Documents/test" },
                },
                completion = {
                  min_chars = 2,
                  match_case = false,
                  create_new = false,
                },
                picker = { name = "mini.pick" },
                ui = { enable = false },
                daily_notes = {
                  folder = "daily",
                  date_format = "%Y-%m-%d",
                  alias_format = "%B %-d, %Y",
                  default_tags = { "daily" },
                },
                attachments = {
                  folder = "attachments",
                  img_name_func = function()
                    return string.format("%s-%s",
                      os.date("%Y-%m-%d-%H%M%S"),
                      vim.fn.input("Image name: "))
                  end,
                },
              },
            },
            {
              "krissen/blink-cmp-bibtex",
              ft = { "markdown", "tex", "plaintex" },
              opts = {
                global_files = discover_bib_files,
                preview_style = "apa",
              },
            },
            -- Merge bibtex provider into blink.cmp sources.
            -- lazy.nvim deep-merges opts for the same plugin across specs.
            -- NOTE: Can't use `default = function(list)` pattern because
            -- obsidian.nvim's check_completion_availability iterates blink.cmp
            -- config and calls any functions it finds, passing nil.
            {
              "saghen/blink.cmp",
              opts = {
                sources = {
                  per_filetype = {
                    markdown = { "lsp", "path", "snippets", "buffer", "spell", "bibtex" },
                    tex = { "lsp", "path", "snippets", "buffer", "spell", "bibtex" },
                    plaintex = { "lsp", "path", "snippets", "buffer", "spell", "bibtex" },
                  },
                  providers = {
                    bibtex = {
                      name = "BibTeX",
                      module = "blink-cmp-bibtex",
                      opts = {},
                      async = true,
                      override = {
                        get_trigger_characters = function()
                          return { "@" }
                        end,
                      },
                      min_keyword_length = 1,
                    },
                  },
                },
              },
            },
          },

          lsp = {
            servers = { "obsidian_ls" },
            configs = {},
          },
        }
      '';

      nvimFeatureDrv = pkgs.runCommand "nvim-research-features" { } ''
        mkdir -p "$out/lua/lean/research"
        cat > "$out/lua/lean/research/init.lua" << 'INIT_EOF'
        ${researchInitLua}
        INIT_EOF
      '';

    in
    {
      # =======================================================================
      # Nvim research feature — activation-merged plugin layer
      # =======================================================================
      home.activation.mergeNvimFeatures = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
        nvimDir="${config.xdg.configHome}/nvim"
        featureSrc="${nvimFeatureDrv}"

        # Resolve the store symlink so we can add files inside the directory.
        if [ -L "$nvimDir" ]; then
          target=$(readlink -f "$nvimDir")
          rm "$nvimDir"
          cp -r "$target" "$nvimDir"
        fi

        # Layer feature files on top of the base config.
        # Store files/dirs are read-only; fix permissions before mutating.
        if [ -d "$featureSrc" ]; then
          rm -rf "$nvimDir/lua/lean/research" 2>/dev/null || {
            chmod -R u+w "$nvimDir/lua/lean/research" 2>/dev/null
            rm -rf "$nvimDir/lua/lean/research"
          }
          cp -r --no-preserve=mode "$featureSrc/." "$nvimDir/"
        fi
      '';
    };
}
