# ==========================================================================
# OBSIDIAN NVIM INTEGRATION
# ==========================================================================
# Neovim plugin layer for the Obsidian vault (~/Documents/me/vault/research).
# Generates lazy.nvim plugin specs + blink-cmp bibtex source + obsidian_ls
# LSP registration as Lua files, then merges them into the nvim config
# directory via a home.activation hook.
#
# ARCHITECTURE: The base nvim config (homeManager.nvim) deploys via
# xdg.configFile."nvim" = { source = derivation; recursive = true; } which
# creates a symlink to the Nix store. Feature modules cannot add files
# alongside a store symlink via xdg.configFile (HM can't write inside store
# paths). The activation hook resolves the symlink, copies the directory,
# and layers feature files on top. See decisions.md #25 for rationale.
#
# When this module is NOT imported, none of these files exist and the base
# nvim config loads without research plugins — zero cost.
# ==========================================================================
{ inputs, ... }: {
  flake.modules.homeManager.obsidian =
    { config, lib, pkgs, ... }:
    let
      vaultPath = "~/Documents/me/vault/research";

      researchInitLua = ''
        -- Research feature: obsidian.nvim + blink-cmp-bibtex + obsidian_ls
        -- Generated by modules/research/obsidian.nix — do not edit manually.
        return {
          plugins = {
            {
              "obsidian-nvim/obsidian.nvim",
              version = "*",
              ft = "markdown",
              dependencies = { "nvim-lua/plenary.nvim" },
              opts = {
                workspaces = {
                  { name = "research", path = "${vaultPath}" },
                },
                completion = {
                  min_chars = 2,
                  match_case = false,
                  create_new = false,
                },
                picker = { name = nil },
                ui = { enable = false },
                follow_url_func = function(url)
                  vim.fn.jobstart({ "xdg-open", url })
                end,
                daily_notes = {
                  folder = "daily",
                  date_format = "%Y-%m-%d",
                  alias_format = "%B %-d, %Y",
                  default_tags = { "daily" },
                },
                attachments = {
                  img_folder = "attachments",
                  img_name_func = function()
                    return string.format("%s-%s",
                      os.date("%Y-%m-%d-%H%M%S"),
                      vim.fn.input("Image name: "))
                  end,
                },
              },
            },
            {
              "krissen/blink-cmp-bibtex",
              ft = { "markdown", "tex", "plaintex" },
              dependencies = { "saghen/blink.cmp" },
              opts = {
                global_files = { vim.fn.expand("${vaultPath}/references.bib") },
                preview_style = "apa",
              },
            },
            -- Merge bibtex provider into blink.cmp sources.
            -- lazy.nvim deep-merges opts for the same plugin across specs.
            {
              "saghen/blink.cmp",
              opts = {
                sources = {
                  default = { "lsp", "path", "snippets", "buffer" },
                  per_filetype = {
                    markdown = { "lsp", "path", "snippets", "buffer", "spell", "bibtex" },
                    tex = { "lsp", "path", "snippets", "buffer", "spell", "bibtex" },
                    plaintex = { "lsp", "path", "snippets", "buffer", "spell", "bibtex" },
                  },
                  providers = {
                    bibtex = {
                      name = "BibTeX",
                      module = "blink-cmp-bibtex",
                      opts = {},
                      async = true,
                      min_keyword_length = 2,
                    },
                  },
                },
              },
            },
          },

          lsp = {
            servers = { "obsidian_ls" },
            configs = {},
          },
        }
      '';

      researchLspLua = ''
        -- Research LSP servers — generated by modules/research/obsidian.nix
        return {
          servers = { "obsidian_ls" },
          configs = {},
        }
      '';

      nvimFeatureDrv = pkgs.runCommand "nvim-research-features" { } ''
        mkdir -p "$out/lua/lean/research"
        cat > "$out/lua/lean/research/init.lua" << 'INIT_EOF'
        ${researchInitLua}
        INIT_EOF
        cat > "$out/lua/lean/research/lsp.lua" << 'LSP_EOF'
        ${researchLspLua}
        LSP_EOF
      '';

    in
    {
      home.activation.mergeNvimFeatures = lib.hm.dag.entryAfter [ "linkGeneration" ] ''
        nvimDir="${config.xdg.configHome}/nvim"
        featureSrc="${nvimFeatureDrv}"

        # Resolve the store symlink so we can add files inside the directory.
        if [ -L "$nvimDir" ]; then
          target=$(readlink -f "$nvimDir")
          rm "$nvimDir"
          cp -r "$target" "$nvimDir"
        fi

        # Layer feature files on top of the base config.
        # Store files/dirs are read-only; fix permissions before mutating.
        if [ -d "$featureSrc" ]; then
          rm -rf "$nvimDir/lua/lean/research" 2>/dev/null || {
            chmod -R u+w "$nvimDir/lua/lean/research" 2>/dev/null
            rm -rf "$nvimDir/lua/lean/research"
          }
          cp -r --no-preserve=mode "$featureSrc/." "$nvimDir/"
        fi
      '';
    };
}
